# Generated by Django 4.1.1 on 2022-09-15 08:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 8, 5, 364605, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 8, 8, 5, 364669, tzinfo=datetime.timezone.utc)),
        ),
    ]
