# Generated by Django 4.1.1 on 2022-09-18 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_activity_options_activity_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 11, 21, 59, 894807, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 11, 21, 59, 894851, tzinfo=datetime.timezone.utc)),
        ),
    ]
